// Generated by scripts/generate-content-index.mjs. Do not edit manually.
import type { Achievement, Person, Project, Story } from "@/src/types";

import projectsDocument0 from "../content/projects/project-one.json";
import projectsDocument1 from "../content/projects/test-draft-project.json";
import projectsDocument2 from "../content/projects/test-practice-project-2026.json";
import peopleDocument0 from "../content/people/person-jia.json";
import peopleDocument1 from "../content/people/test-archived-person.json";
import peopleDocument2 from "../content/people/test-person-a.json";
import storiesDocument0 from "../content/stories/story-example.json";
import storiesDocument1 from "../content/stories/test-review-story.json";
import storiesDocument2 from "../content/stories/test-story-2026.json";
import achievementsDocument0 from "../content/achievements/achievement-example.json";
import achievementsDocument1 from "../content/achievements/test-achievement-file.json";

export const generatedProjects: Project[] = [
  projectsDocument0 as Project,
  projectsDocument1 as Project,
  projectsDocument2 as Project,
];

export const generatedPeople: Person[] = [
  peopleDocument0 as Person,
  peopleDocument1 as Person,
  peopleDocument2 as Person,
];

export const generatedStories: Story[] = [
  storiesDocument0 as Story,
  storiesDocument1 as Story,
  storiesDocument2 as Story,
];

export const generatedAchievements: Achievement[] = [
  achievementsDocument0 as Achievement,
  achievementsDocument1 as Achievement,
];
